name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env: 
  global_env: global

jobs:
  build_unix:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: pwd
