name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env: 
  global_env: global

jobs:  
  sys_info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: check tools
        run: |
          cmake --version
          gcc --version
        
  build_unix:
    needs: [sys_info]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: build
        run: |
          cmake ./
          cmake --build .
          
      - name: save_test
        run: |
          touch save_test
          cat test/GHA-frac.test > save_test
          
      - name: share_artifact
        uses: actions/upload-artifact@v2
        with:
          name: save_test
          path: ./save_test
  
  test:
    needs: [build_unix]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: download_test
        uses: actions/download-artifact@v2
        with:
          name: save_test
          
      - name: setting
        run: chmod ugo+rwx save_test
        
      - name: google_test
        run: |
          ./save_test
    
    
          
